name: L00_Hello CI

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/mainTest.cpp'
      
jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    name: Get changed files
    steps:
    - name: Changed Files
      id: thuytt_files
      uses: Ana06/get-changed-files@v2.2.0
    - name: Printing
      run: |
        echo "Modified:"
        echo "${{ steps.thuytt_files.outputs.modified }}"
    outputs: 
      abc: ${{ steps.thuytt_files.outputs.modified }}
  
#   check_in_folder:
#     needs: get_changed_files
#     runs-on: ubuntu-latest
#     name: Check pattern
#     steps:
#     - name: Check pattern L1
#       if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L1-GuessIt') }}
#       run: |
#         echo "bingo contain ${{needs.get_changed_files.outputs.abc}}"
#     - name: Check L0
#       if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L0-Hello') }}
#       run: |
#         echo "bingo contain ${{needs.get_changed_files.outputs.abc}}"

  check_AdvProg_L0:
    needs: get_changed_files
    runs-on: ubuntu-latest
    name: Check AdvProg_L0_Hello
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L0-Hello') }}
    steps:
      - uses: actions/checkout@v2
      - name: update
        run: sudo apt-get update
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: configure
        working-directory: ./AdvProg_L0-Hello
        run: |
          ./configure
          make
          make test
#       - name: make AdvProg_L0
#         working-directory: ./AdvProg_L0-Hello
#         run: make
#       - name: make test AdvProg_L0
#         working-directory: ./AdvProg_L0-Hello
#         run: make test
  
  # AdvProg_L1-GuessIt
  check_AdvProg_L1:
    needs: get_changed_files
    runs-on: ubuntu-latest
    name: Check AdvProg_L1_GuessIt
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L1-GuessIt') }}
    steps:
      - uses: actions/checkout@v2
      - name: update
        run: sudo apt-get update
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: configure
        working-directory: ./AdvProg_L1-GuessIt
        run: ./configure
      - name: make
        working-directory: ./AdvProg_L1-GuessIt
        run: make
      - name: make test
        working-directory: ./AdvProg_L1-GuessIt
        run: make test

#   # AdvProg_L2_Calculus
#   check_AdvProg_L2:
#     needs: get_changed_files
#     runs-on: ubuntu-latest
#     name: Check AdvProg_L2_Calculus
#     if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L2_Calculus') }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: update
#         run: sudo apt-get update
#       - name: install cppunit
#         run: sudo apt install -y libcppunit-dev
#       - name: configure
#         working-directory: ./AdvProg_L2_Calculus
#         run: ./configure
#       - name: make
#         working-directory: ./AdvProg_L2_Calculus
#         run: make
#       - name: make test
#         working-directory: ./AdvProg_L2_Calculus
#         run: make test
        
#   # AdvProg_L3_HangMan
#   check_AdvProg_L3:
#     needs: get_changed_files
#     runs-on: ubuntu-latest
#     name: Check AdvProg_L3_HangMan
#     if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L3_HangMan') }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: update
#         run: sudo apt-get update
#       - name: install cppunit
#         run: sudo apt install -y libcppunit-dev
#       - name: configure
#         working-directory: ./AdvProg_L3_HangMan
#         run: ./configure
#       - name: make
#         working-directory: ./AdvProg_L3_HangMan
#         run: make
#       - name: make test
#         working-directory: ./AdvProg_L3_HangMan
#         run: make test
  
#   # AdvProg_L4-SimpleAI
#   check_AdvProg_L4:
#     needs: get_changed_files
#     runs-on: ubuntu-latest
#     name: Check AdvProg_L4-SimpleAI
#     if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L4-SimpleAI') }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: update
#         run: sudo apt-get update
#       - name: install cppunit
#         run: sudo apt install -y libcppunit-dev
#       - name: configure
#         working-directory: ./AdvProg_L4-SimpleAI
#         run: ./configure
#       - name: make
#         working-directory: ./AdvProg_L4-SimpleAI
#         run: make
#       - name: make test
#         working-directory: ./AdvProg_L4-SimpleAI
#         run: make test
        
#   # AdvProg_L6-Painter
#   check_AdvProg_L6:
#     needs: get_changed_files
#     runs-on: ubuntu-latest
#     name: Check AdvProg_L6-Painter
#     if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L6-Painter') }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: update
#         run: sudo apt-get update
#       - name: install cppunit
#         run: sudo apt install -y libcppunit-dev
#       - name: install sdl2
#         run: sudo apt install libsdl2-dev
#       - name: install sdl2image
#         run: sudo apt install libsdl2-image-dev
#       - name: configure
#         working-directory: ./AdvProg_L6-Painter
#         run: ./configure
#       - name: make
#         working-directory: ./AdvProg_L6-Painter
#         run: make
#       - name: make test
#         working-directory: ./AdvProg_L6-Painter
#         run: make test
        
#   # AdvProg_L7-Snake
#   check_AdvProg_L7:
#     needs: get_changed_files
#     runs-on: ubuntu-latest
#     name: Check AdvProg_L7_Snake
#     if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L7_Snake') }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: update
#         run: sudo apt-get update
#       - name: install cppunit
#         run: sudo apt install -y libcppunit-dev
#       - name: install sdl2
#         run: sudo apt install libsdl2-dev
#       - name: install sdl2image
#         run: sudo apt install libsdl2-image-dev
#       - name: configure
#         working-directory: ./AdvProg_L7_Snake
#         run: ./configure
#       - name: make
#         working-directory: ./AdvProg_L7_Snake
#         run: make
#       - name: make test
#         working-directory: ./AdvProg_L7_Snake
#         run: make test



      # # AdvProg_L6-Painter
      # - name: configure
      #   working-directory: ./AdvProg_L6-Painter
      #   run: ./configure
      # - name: make AdvProg_L6
      #   working-directory: ./AdvProg_L6-Painter
      #   run: make
      # - name: make test AdvProg_L6
      #   continue-on-error: true
      #   working-directory: ./AdvProg_L6-Painter
      #   run: make test

      # # AdvProg_L7-Snake
      # - name: configure privelige
      #   working-directory: ./AdvProg_L7-Snake
      #   run: chmod +x configure
      # - name: configure
      #   working-directory: ./AdvProg_L7-Snake
      #   run: ./configure
      # - name: make AdvProg_L7
      #   working-directory: ./AdvProg_L7-Snake
      #   run: make
      # - name: make test AdvProg_L7
      #   continue-on-error: true
      #   working-directory: ./AdvProg_L7-Snake
      #   run: make test
