name: L00_Hello CI

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/mainTest.cpp'
      
jobs:
  run_7_jobs:
    runs-on: ubuntu-latest
    name: Run 7 jobs
    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      
      # AdvProg_L0-Hello
      - name: configure
        working-directory: ./AdvProg_L0-Hello
        run: ./configure
      - name: make AdvProg_L0
        working-directory: ./AdvProg_L0-Hello
        run: make
      - name: make test AdvProg_L0
        working-directory: ./AdvProg_L0-Hello
        run: make test

      # AdvProg_L1-GuessIt
      - name: configure
        if: always()
        working-directory: ./AdvProg_L1-GuessIt
        run: ./configure
      - name: make AdvProg_L1
        if: always()
        working-directory: ./AdvProg_L1-GuessIt
        run: make
      - name: make test AdvProg_L1
        if: always()
        working-directory: ./AdvProg_L1-GuessIt
        run: make test

      # AdvProg_L2-Calculus
      - name: configure
        working-directory: ./AdvProg_L2-Calculus
        run: ./configure
      - name: make AdvProg_L2
        working-directory: ./AdvProg_L2-Calculus
        run: make
      - name: make test AdvProg_L2
        working-directory: ./AdvProg_L2-Calculus
        run: make test

      # AdvProg_L3-HangMan
      - name: configure
        working-directory: ./AdvProg_L3-HangMan
        run: ./configure
      - name: make AdvProg_L3
        working-directory: ./AdvProg_L3-HangMan
        run: make
      - name: make test AdvProg_L3
        working-directory: ./AdvProg_L3-HangMan
        run: make test

      # AdvProg_L4-SimpleAI
      - name: configure
        working-directory: ./AdvProg_L4-SimpleAI
        run: ./configure
      - name: make AdvProg_L4
        working-directory: ./AdvProg_L4-SimpleAI
        run: make
      - name: make test AdvProg_L4
        working-directory: ./AdvProg_L4-SimpleAI
        run: make test

      # AdvProg_L6-Painter
      - name: configure
        working-directory: ./AdvProg_L6-Painter
        run: ./configure
      - name: make AdvProg_L6
        working-directory: ./AdvProg_L6-Painter
        run: make
      - name: make test AdvProg_L6
        working-directory: ./AdvProg_L6-Painter
        run: make test

      # AdvProg_L7-Snake
      - name: configure
        working-directory: ./AdvProg_L7-Snake
        run: ./configure
      - name: make AdvProg_L7
        working-directory: ./AdvProg_L7-Snake
        run: make
      - name: make test AdvProg_L7
        working-directory: ./AdvProg_L7-Snake
        run: make test