name: L00_Hello CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/mainTest.cpp'
      
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello world job
    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: configure
        run: |
                cd AdvProg_L0-Hello
                ./configure
      - name: make
        run: |
                cd AdvProg_L0-Hello
                make
      - name: make test
        run: |
                cd AdvProg_L0-Hello
                make test
